#ifndef C_DATASTRUCTURES_DOUBLYLINKEDLISTDEQUETEST_H
#define C_DATASTRUCTURES_DOUBLYLINKEDLISTDEQUETEST_H

#include "../../../../ErrorsTestStruct.h"

void doublyLinkedListDequeUnitTest();

#endif //C_DATASTRUCTURES_DOUBLYLINKEDLISTDEQUETEST_H
