#ifndef C_DATASTRUCTURES_TXTFILELOADERTEST_H
#define C_DATASTRUCTURES_TXTFILELOADERTEST_H

#include "../../../ErrorsTestStruct.h"

void txtFileLoaderAlgUnitTest();

#endif //C_DATASTRUCTURES_TXTFILELOADERTEST_H
