#ifndef C_DATASTRUCTURES_HEAPPRIORITYQUEUETEST_H
#define C_DATASTRUCTURES_HEAPPRIORITYQUEUETEST_H

#include "../../../../ErrorsTestStruct.h"

void heapPriorityQueueUnitTest(void);


#endif //C_DATASTRUCTURES_HEAPPRIORITYQUEUETEST_H
