#ifndef C_DATASTRUCTURES_LINKEDLISTQUEUETEST_H
#define C_DATASTRUCTURES_LINKEDLISTQUEUETEST_H

#include "../../../../ErrorsTestStruct.h"

void linkedListQueueUnitTest();

#endif //C_DATASTRUCTURES_LINKEDLISTQUEUETEST_H
