var annotated_dup =
[
    [ "ArrayDeque", "struct_array_deque.html", "struct_array_deque" ],
    [ "ArrayList", "struct_array_list.html", "struct_array_list" ],
    [ "ArrayQueue", "struct_array_queue.html", "struct_array_queue" ],
    [ "AVLTNode", "struct_a_v_l_t_node.html", "struct_a_v_l_t_node" ],
    [ "AVLTree", "struct_a_v_l_tree.html", "struct_a_v_l_tree" ],
    [ "BinaryMaxHeap", "struct_binary_max_heap.html", "struct_binary_max_heap" ],
    [ "BinaryMinHeap", "struct_binary_min_heap.html", "struct_binary_min_heap" ],
    [ "BinaryTree", "struct_binary_tree.html", "struct_binary_tree" ],
    [ "BinaryTreeNode", "struct_binary_tree_node.html", "struct_binary_tree_node" ],
    [ "DLinkedListStack", "struct_d_linked_list_stack.html", "struct_d_linked_list_stack" ],
    [ "DoublyLinkedList", "struct_doubly_linked_list.html", "struct_doubly_linked_list" ],
    [ "Entry", "struct_entry.html", "struct_entry" ],
    [ "HashMap", "struct_hash_map.html", "struct_hash_map" ],
    [ "KeyHolder", "struct_key_holder.html", "struct_key_holder" ],
    [ "LinkedList", "struct_linked_list.html", "struct_linked_list" ],
    [ "LinkedListHashMap", "struct_linked_list_hash_map.html", "struct_linked_list_hash_map" ],
    [ "LinkedListQueue", "struct_linked_list_queue.html", "struct_linked_list_queue" ],
    [ "Node", "struct_node.html", "struct_node" ],
    [ "PriorityQueue", "struct_priority_queue.html", "struct_priority_queue" ],
    [ "SplayNode", "struct_splay_node.html", "struct_splay_node" ],
    [ "SplayTree", "struct_splay_tree.html", "struct_splay_tree" ],
    [ "SQueue", "struct_s_queue.html", "struct_s_queue" ],
    [ "Stack", "struct_stack.html", "struct_stack" ],
    [ "String", "struct_string.html", "struct_string" ],
    [ "Trie", "struct_trie.html", "struct_trie" ],
    [ "Vector", "struct_vector.html", "struct_vector" ]
];