#ifndef C_DATASTRUCTURES_DLINKEDLISTSTACKTEST_H
#define C_DATASTRUCTURES_DLINKEDLISTSTACKTEST_H

#include "../../../../ErrorsTestStruct.h"

void doublyLinkedListStackUnitTest();

#endif //C_DATASTRUCTURES_DLINKEDLISTSTACKTEST_H
