#ifndef C_DATASTRUCTURES_DOUBLYLINKEDLISTHASHMAPTEST_H
#define C_DATASTRUCTURES_DOUBLYLINKEDLISTHASHMAPTEST_H

#include "../../../../ErrorsTestStruct.h"

void doublyLinkedListHashMapUnitTest();

#endif //C_DATASTRUCTURES_DOUBLYLINKEDLISTHASHMAPTEST_H
